### ISSUE TITLE
Unable to delete multi-quesitons

### ISSUE THREAD

**Issue by OctaveSec** [tamuctf/CTFd-multi-question-plugin#2]
Unable to delete any questions added using the multi-question-plugin. Tested with CTFd v1.2  on Ubuntu 18.04 and Debian 9.

**Comment by ameserole** [comment]
I can't seem to reproduce it on my end with CTFd v1.2 and Ubuntu 18.04. Can you add some more details please? What are the exact steps you are taking?  Is there a traceback? Are you using any other challenge plugins?

**Comment by OctaveSec** [comment]
It might be something I am doing. It all functions correctly, except deleting the questions I added. It seems to load correctly, so I am at a loss. I can add and delete standard questions. No other plugins are being used. Please let me know if you need anything more specific. 

***@ctfOS-debian:~/CTFd/CTFd/plugins$ ls
challenges  __init__.py  keys

***@ctfOS-debian:~/CTFd/CTFd/plugins$ sudo git clone https://github.com/tamuctf/CTFd-multi-question-plugin.git
Resolving deltas: 100% (53/53), done.

***@ctfOS-debian:~/CTFd/CTFd/plugins$ ls 
challenges  CTFd-multi-question-plugin  __init__.py  keys

***@ctfOS-debian:~/CTFd/CTFd/plugins$ ls CTFd-multi-question-plugin/
challenge-assets  __init__.py  pics  README.md

***@ctfOS-debian:~/CTFd$ sudo docker-compose up
...
ctfd_1   | .db is ready
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.CTFd-multi-question-plugin' from '/opt/CTFd/CTFd/plugins/CTFd-multi-question-plugin/__init__.py'>
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.keys' from '/opt/CTFd/CTFd/plugins/keys/__init__.py'>
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.challenges' from '/opt/CTFd/CTFd/plugins/challenges/__init__.py'>
ctfd_1   | Starting CTFd
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.CTFd-multi-question-plugin' from '/opt/CTFd/CTFd/plugins/CTFd-multi-question-plugin/__init__.py'>
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.CTFd-multi-question-plugin' from '/opt/CTFd/CTFd/plugins/CTFd-multi-question-plugin/__init__.py'>
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.CTFd-multi-question-plugin' from '/opt/CTFd/CTFd/plugins/CTFd-multi-question-plugin/__init__.py'>
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.CTFd-multi-question-plugin' from '/opt/CTFd/CTFd/plugins/CTFd-multi-question-plugin/__init__.py'>
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.keys' from '/opt/CTFd/CTFd/plugins/keys/__init__.py'>
ctfd_1   |  * Loaded module, <module 'CTFd.plugins.challenges' from '/opt/CTFd/CTFd/plugins/challenges/__init__.py'>
ctfd_1   | [08/29/2018 16:54:42] CTFadmin submitted 5 with kpm 0
ctfd_1   | [08/29/2018 16:54:59] CTFadmin submitted 1 with kpm 1
cache_1  | 1:M 29 Aug 17:00:21.352 * 100 changes in 300 seconds. Saving...
cache_1  | 1:M 29 Aug 17:00:21.353 * Background saving started by pid 15
cache_1  | 15:C 29 Aug 17:00:21.512 * DB saved on disk
cache_1  | 15:C 29 Aug 17:00:21.513 * RDB: 0 MB of memory used by copy-on-write
cache_1  | 1:M 29 Aug 17:00:21.554 * Background saving terminated with success

**Comment by ameserole** [comment]
Thanks, I was able to reproduce it now. I'm guessing it has something to do with running it with docker compose. Ill look into it and see if I can figure out what is wrong.

**Comment by ameserole** [comment]
https://github.com/tamuctf/CTFd-multi-question-plugin/commit/fadbe9573ef38efe47ddcfdb6100b4b634eae318 should fix it. 
Try it now and let me know if you still have any issues.

**Comment by OctaveSec** [comment]
That worked! Thanks for building this plugin and the prompt fix.

**Comment by ameserole** [comment]
Great, thanks for pointing out the bug.
